### ISSUE TITLE
Build farmer handoff 2018-01-03

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/build_farmer#78]
## Buildfarm health

Nodes are healthy overall. This shift has been mostly about getting the machines ready for the Ardent release.
- `dosa` is back online with some workarounds to run with SIP enabled (prevent massive slow-down). Dosa is also now running the jenkins client as a service without significant performance hit.
- `linux_slave_on_master` has been taken offline as CPU spikes when building were preventing the masters proper functioning. We rolled out another node `linux4` for now 
- all nodes have been updated to the latest version of system packages and dependency before the release. Several packages got updated since preventing users to have ros2 working out-of-the-box from binaries (more information at #74)
- all nodes can run jobs with OpenSplice

#### Outstanding issues

- [x] Coverage job failing consistently (#76)

#### Pending Tasks

- [ ] Roll-out lauchd configuration to mini1 and mini2 sequentially (https://github.com/ros2/ci/pull/118)
- [ ] Investigate packet.net host issue (#42)
- [ ] Investigate rogue process causing arm jobs to hang on exit (#72) 
- [x] Support VS2017 (#69) 
- [ ] Upgrade eatable to Windows 10 (#17)

#### Recurring tasks

 - system and package (brew/chocolatey) updates on MacOS and Windows machines (see #74)
 - system update on linux nodes
 - update the master node (#66) 

## Test suite health

* [x] Some tests are getting really flaky failing even on regular ci:
  * test_composition__rmw_fastrtps_cpp (timing out on all platforms)

**Comment by nuclearsandwich** [comment]
> Upgrade eatable to Windows 10 (#17)

This is on my docket for Friday this week.



> Roll-out lauchd configuration to mini1 and mini2 sequentially (ros2/ci#118)

I'm happy to do this rollout or assign it to the current build farmer.

**Comment by dirk-thomas** [comment]
> > Roll-out lauchd configuration to mini1 and mini2 sequentially (ros2/ci#118)

> I'm happy to do this rollout or assign it to the current build farmer.

Please feel free to do it. I don't expect to have much time for build farmer related work.

**Comment by dirk-thomas** [comment]
* [x] ros2/ci#120: resolved differences between the configuration stored in this repo and the actual configuration on Jenkins
* [x] #73: detecting CMake warnings without a filename:linenumber
* [x] #76: fix coverage job
* [x] #69: Support VS2017, pending public Connext release, upstream fixes for Windows compiler warnings (see ros2/ci#122)

---

Closing obsolete tickets:
* [x] #14
* [x] #40
* [x] #47 
* [x] ros2/demos#143

---

New tickets:

* [x] #80 test_composition__rmw_fastrtps_cpp

**Comment by dirk-thomas** [comment]
Closing in favor of #82.
