### ISSUE TITLE
Build farmer handoff 2018-01-30

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/build_farmer#82]
## Buildfarm health

Nodes are healthy overall. Especially with the updated macOS machines they reliably reconnected.

I addressed some long standing issues and cleaned up obsolete stuff. I also prepared the transisition to Visual Studio 2017. For details see #78.

#### Pending Tasks

- [ ] Investigate packet.net host issue (#42)
- [ ] Investigate rogue process causing arm jobs to hang on exit (#72) 
- [ ] Switch to VS2017 once Connext provides public binaries (ros2/ci#122) 
- [ ] Upgrade eatable to Windows 10 (#17)

#### Recurring tasks

 - system and package (brew/chocolatey) updates on MacOS and Windows machines (see #74)
 - system update on linux nodes
 - update the master node (#66) 

## Test suite health

* Same as for a long time: the composition tests are frequent "fails" in the nightlies
